font-family = "{{ conf.theme.common.monospace_font }}"
font-size = {{ conf.font_size }}
theme = {{ conf.theme.ghostty.dark }}
# theme = dark:{{ conf.theme.ghostty.dark }},light:{{ conf.theme.ghostty.light }}
shell-integration-features = ssh-terminfo,ssh-env,sudo
window-decoration = none
quit-after-last-window-closed = true
quick-terminal-size = 80%
keybind = ctrl+enter=unbind
copy-on-select = clipboard
clipboard-read = allow
clipboard-write = allow

