font-family = "{{ conf.theme.monospace_font }}"
font-size = {{ conf.font_size }}
theme = {{ conf.theme.nice_name }}
# theme = dark:{{ conf.theme.nice_name }},light:{{ conf.theme.nice_light_name }}
shell-integration-features = ssh-terminfo,ssh-env,sudo
window-decoration = none
quit-after-last-window-closed = true
quick-terminal-size = 80%
keybind = ctrl+enter=unbind
